In [44]:
import csv
import pandas as pd
import numpy as np
import torch

In [45]:
data = pd.read_csv("Food_production.csv")
data.head()

Food product  Land use change  Animal Feed  Farm  Processing  \
0  Wheat & Rye (Bread)              0.1          0.0   0.8         0.2   
1         Maize (Meal)              0.3          0.0   0.5         0.1   
2        Barley (Beer)              0.0          0.0   0.2         0.1   
3              Oatmeal              0.0          0.0   1.4         0.0   
4                 Rice              0.0          0.0   3.6         0.1   

   Transport  Packging  Retail  Total_emissions  \
0        0.1       0.1     0.1              1.4   
1        0.1       0.1     0.0              1.1   
2        0.0       0.5     0.3              1.1   
3        0.1       0.1     0.0              1.6   
4        0.1       0.1     0.1              4.0   

   Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)  ...  \
0                                                NaN         ...   
1                                                NaN         ...   
2                                                NaN         ...   
3                                           4.281357         ...   
4                                           9.514379         ...   

   Freshwater withdrawals per 100g protein (liters per 100g protein)  \
0                                                NaN                   
1                                                NaN                   
2                                                NaN                   
3                                         371.076923                   
4                                        3166.760563                   

   Freshwater withdrawals per kilogram (liters per kilogram)  \
0                                                NaN           
1                                                NaN           
2                                                NaN           
3                                              482.4           
4                                             2248.4           

   Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)  \
0                                                NaN              
1                                                NaN              
2                                                NaN              
3                                           0.945482              
4                                           1.207271              

   Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)  \
0                                                NaN                      
1                                                NaN                      
2                                                NaN                      
3                                           1.907692                      
4                                           6.267606                      

   Land use per 1000kcal (m² per 1000kcal)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                 2.897446   
4                                 0.759631   

   Land use per kilogram (m² per kilogram)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      7.6   
4                                      2.8   

   Land use per 100g protein (m² per 100g protein)  \
0                                              NaN   
1                                              NaN   
2                                              NaN   
3                                         5.846154   
4                                         3.943662   

   Scarcity-weighted water use per kilogram (liters per kilogram)  \
0                                                NaN                
1                                                NaN                
2                                                NaN                
3                     

In [46]:
data_filter = data[["Food product", "Total_emissions"]]


In [47]:
data_filter

Food product  Total_emissions
0   Wheat & Rye (Bread)              1.4
1          Maize (Meal)              1.1
2         Barley (Beer)              1.1
3               Oatmeal              1.6
4                  Rice              4.0
5              Potatoes              0.3
6               Cassava              0.9
7            Cane Sugar              2.6
8            Beet Sugar              1.4
9          Other Pulses              1.6
10                 Peas              0.8
11                 Nuts              0.2
12           Groundnuts              2.4
13              Soymilk              1.0
14                 Tofu              3.0
15          Soybean Oil              6.0
16             Palm Oil              7.6
17        Sunflower Oil              3.5
18         Rapeseed Oil              3.7
19            Olive Oil              6.0
20             Tomatoes              1.4
21       Onions & Leeks              0.3
22      Root Vegetables              0.3
23            Brassicas              0.4
24     Other Vegetables              0.5
25         Citrus Fruit              0.3
26              Bananas              0.8
27               Apples              0.3
28     Berries & Grapes              1.1
29                 Wine              1.4
30          Other Fruit              0.7
31               Coffee             16.5
32       Dark Chocolate             18.7
33     Beef (beef herd)             59.6
34    Beef (dairy herd)             21.1
35        Lamb & Mutton             24.5
36             Pig Meat              7.2
37         Poultry Meat              6.1
38                 Milk              2.8
39               Cheese             21.2
40                 Eggs              4.5
41        Fish (farmed)              5.1
42     Shrimps (farmed)             11.8

In [48]:
data_filter["polish_name"] = ["Pszenica i żyto (chleb)",
"Kukurydza (mączka)",
"Jęczmień (piwo)",
"Płatki owsiane",
"Ryż",
"Ziemniaki",
"Cassava",
"Cukier trzcinowy",
"Cukier buraczany",
"Inne rośliny strączkowe",
"Groch",
"Orzechy",
"Orzeszki ziemne",
"Mleko sojowe",
"Tofu",
"Olej sojowy",
"Olej palmowy",
"Olej słonecznikowy",
"Olej rzepakowy",
"Oliwa z oliwek",
"Pomidory",
"Cebula i pory",
"Warzywa korzeniowe",
"Warzywa kapustne",
"Pozostałe warzywa",
"Owoce cytrusowe",
"Banany",
"Jabłka",
"Jagody i winogrona",
"Wino",
"Pozostałe owoce",
"Kawa",
"Ciemna czekolada",
"Wołowina (stado bydła)",
"Wołowina (stada mleczne)",
"Jagnięcina i baranina",
"Mięso wieprzowe",
"Mięso drobiowe",
"Mleko",
"Ser",
"Jaja",
"Ryby (hodowlane)",
"Krewetki (hodowlane)"]


<ipython-input-48-0e1d7ed8dfed>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filter["polish_name"] = ["Pszenica i żyto (chleb)",


In [49]:
data_filter.head()

Food product  Total_emissions              polish_name
0  Wheat & Rye (Bread)              1.4  Pszenica i żyto (chleb)
1         Maize (Meal)              1.1       Kukurydza (mączka)
2        Barley (Beer)              1.1          Jęczmień (piwo)
3              Oatmeal              1.6           Płatki owsiane
4                 Rice              4.0                      Ryż

In [50]:
import random
dataset = []
X = 0
Y = 0

names = np.array(data_filter["polish_name"])
emissions = np.array(data_filter["Total_emissions"])

X = []
Y = []
indexes = list(range(len(emissions)))
print(indexes)

for i in indexes:
    X.append(names[i])
    Y.append(emissions[i])
    
for i in range(100):
    random.shuffle(indexes)
    current_name = names[indexes[0]] + ", " + names[indexes[1]]
    print(names[indexes[0]] + ", " + names[indexes[1]])
    print(emissions[indexes[0]], emissions[indexes[1]], (emissions[indexes[0]] + emissions[indexes[1]])/2)
    X.append(current_name)
    current_emission = (emissions[indexes[0]] + emissions[indexes[1]])/2
    Y.append(current_emission)

for i in range(1000):
    random.shuffle(indexes)
    current_name = names[indexes[0]] + ", " + names[indexes[1]] + ", " + names[indexes[2]]
    X.append(current_name)
    current_emission = (emissions[indexes[0]] + emissions[indexes[1]] + emissions[indexes[2]])/3
    print(current_name)
    print(emissions[indexes[0]], emissions[indexes[1]], emissions[indexes[1]], current_emission)
    Y.append(current_emission)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
Olej palmowy, Orzechy
7.6 0.2 3.9
Ser, Inne rośliny strączkowe
21.2 1.6 11.4
Jaja, Wołowina (stada mleczne)
4.5 21.1 12.8
Jabłka, Cukier trzcinowy
0.30000000000000004 2.6 1.4500000000000002
Warzywa kapustne, Ser
0.4 21.2 10.799999999999999
Owoce cytrusowe, Ziemniaki
0.3 0.30000000000000004 0.30000000000000004
Tofu, Ryż
3.0 4.0 3.5
Mięso drobiowe, Olej palmowy
6.1000000000000005 7.6 6.85
Olej sojowy, Tofu
5.999999999999999 3.0 4.5
Orzeszki ziemne, Banany
2.4 0.7999999999999999 1.5999999999999999
Jabłka, Oliwa z oliwek
0.30000000000000004 6.0 3.15
Olej palmowy, Olej rzepakowy
7.6 3.7 5.65
Banany, Płatki owsiane
0.7999999999999999 1.6 1.2
Warzywa korzeniowe, Wino
0.30000000000000004 1.4 0.85
Pozostałe warzywa, Krewetki (hodowlane)
0.5 11.8 6.15
Płatki owsiane, Ciemna czekolada
1.6 18.7 10.15
Groch, Pszenica i żyto (chleb)
0.7999

1.4000000000000004 0.30000000000000004 0.30000000000000004 1.366666666666667
Kawa, Pomidory, Oliwa z oliwek
16.500000000000004 1.4 1.4 7.966666666666668
Banany, Jabłka, Ryby (hodowlane)
0.7999999999999999 0.30000000000000004 0.30000000000000004 2.0666666666666664
Pomidory, Płatki owsiane, Tofu
1.4 1.6 1.6 2.0
Jagody i winogrona, Cassava, Mięso drobiowe
1.1 0.9 0.9 2.7000000000000006
Cukier trzcinowy, Mięso drobiowe, Pomidory
2.6 6.1000000000000005 6.1000000000000005 3.366666666666667
Jęczmień (piwo), Banany, Wołowina (stado bydła)
1.1 0.7999999999999999 0.7999999999999999 20.5
Ryby (hodowlane), Oliwa z oliwek, Ziemniaki
5.1 6.0 6.0 3.8000000000000003
Owoce cytrusowe, Cukier buraczany, Jaja
0.3 1.4 1.4 2.066666666666667
Wołowina (stado bydła), Cassava, Orzechy
59.6 0.9 0.9 20.233333333333334
Pozostałe warzywa, Cukier trzcinowy, Mięso wieprzowe
0.5 2.6 2.6 3.4333333333333336
Ryby (hodowlane), Tofu, Wołowina (stado bydła)
5.1 3.0 3.0 22.566666666666666
Warzywa korzeniowe, Cukier buraczany

0.4 0.7999999999999999 0.7999999999999999 2.933333333333333
Olej słonecznikowy, Ziemniaki, Olej rzepakowy
3.5000000000000004 0.30000000000000004 0.30000000000000004 2.5000000000000004
Warzywa korzeniowe, Jęczmień (piwo), Olej słonecznikowy
0.30000000000000004 1.1 1.1 1.6333333333333335
Oliwa z oliwek, Jagody i winogrona, Tofu
6.0 1.1 1.1 3.3666666666666667
Cukier trzcinowy, Wino, Cassava
2.6 1.4 1.4 1.6333333333333335
Warzywa korzeniowe, Mleko, Pozostałe warzywa
0.30000000000000004 2.8000000000000003 2.8000000000000003 1.2000000000000002
Mięso drobiowe, Kukurydza (mączka), Ser
6.1000000000000005 1.1 1.1 9.466666666666667
Olej słonecznikowy, Owoce cytrusowe, Jagody i winogrona
3.5000000000000004 0.3 0.3 1.6333333333333335
Jaja, Jagnięcina i baranina, Olej słonecznikowy
4.5 24.5 24.5 10.833333333333334
Olej palmowy, Ryż, Cukier buraczany
7.6 4.0 4.0 4.333333333333333
Orzechy, Pozostałe warzywa, Jagody i winogrona
0.2 0.5 0.5 0.6
Jęczmień (piwo), Olej rzepakowy, Pozostałe warzywa
1.1 3.7 

Olej sojowy, Ser, Krewetki (hodowlane)
5.999999999999999 21.2 21.2 13.0
Banany, Jęczmień (piwo), Pomidory
0.7999999999999999 1.1 1.1 1.0999999999999999
Jagody i winogrona, Oliwa z oliwek, Cebula i pory
1.1 6.0 6.0 2.4666666666666663
Cukier buraczany, Płatki owsiane, Mleko sojowe
1.4 1.6 1.6 1.3333333333333333
Groch, Ryż, Pozostałe owoce
0.7999999999999999 4.0 4.0 1.8333333333333333
Cukier trzcinowy, Wołowina (stado bydła), Jagnięcina i baranina
2.6 59.6 59.6 28.900000000000002
Kukurydza (mączka), Cukier buraczany, Jagody i winogrona
1.1 1.4 1.4 1.2
Warzywa korzeniowe, Pszenica i żyto (chleb), Pomidory
0.30000000000000004 1.4000000000000004 1.4000000000000004 1.0333333333333334
Pomidory, Banany, Jęczmień (piwo)
1.4 0.7999999999999999 0.7999999999999999 1.0999999999999999
Ciemna czekolada, Pomidory, Pozostałe warzywa
18.7 1.4 1.4 6.866666666666666
Wołowina (stada mleczne), Ryż, Pozostałe owoce
21.1 4.0 4.0 8.6
Olej rzepakowy, Jagnięcina i baranina, Olej palmowy
3.7 24.5 24.5 11.933333333

1.6 0.5 0.5 0.9666666666666667
Pszenica i żyto (chleb), Cassava, Wołowina (stada mleczne)
1.4000000000000004 0.9 0.9 7.800000000000001
Olej rzepakowy, Jagody i winogrona, Mięso drobiowe
3.7 1.1 1.1 3.633333333333334
Jaja, Kukurydza (mączka), Olej rzepakowy
4.5 1.1 1.1 3.1
Olej palmowy, Mleko sojowe, Cukier trzcinowy
7.6 1.0 1.0 3.733333333333333
Pszenica i żyto (chleb), Ciemna czekolada, Mięso wieprzowe
1.4000000000000004 18.7 18.7 9.1
Jagody i winogrona, Inne rośliny strączkowe, Pomidory
1.1 1.6 1.6 1.3666666666666665
Olej palmowy, Warzywa kapustne, Pozostałe owoce
7.6 0.4 0.4 2.9
Olej sojowy, Oliwa z oliwek, Tofu
5.999999999999999 6.0 6.0 5.0


In [51]:
print(X[100], Y[100])
print(X[200], Y[200])
print(X[300], Y[300])
print(X[400], Y[400])
print(len(X))

Wołowina (stado bydła), Cebula i pory 29.95
Wołowina (stado bydła), Olej sojowy, Jagnięcina i baranina 30.03333333333333
Inne rośliny strączkowe, Jaja, Ryby (hodowlane) 3.733333333333333
Ryby (hodowlane), Oliwa z oliwek, Ziemniaki 3.8000000000000003
1143


In [52]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

sentences = ["Piwo to moje paliwo", "Uwielbiam zajadać się słodkościami."]
model = SentenceTransformer("sdadas/st-polish-paraphrase-from-mpnet")
results = model.encode(sentences, convert_to_tensor=True, show_progress_bar=False)
print(cos_sim(results[0], results[1]))
print(results[0])
# tensor([[0.9794]], device='cuda:0')

tensor([[0.2911]], device='cuda:0')
tensor([-6.7474e-02,  2.6774e-02, -2.4369e-03, -1.5454e-02,  5.9655e-02,
         1.9517e-01, -1.1683e-01, -6.7158e-02,  1.7504e-01, -7.1457e-02,
         3.5706e-02, -5.0024e-02, -2.0156e-03,  1.0760e-01,  1.8166e-01,
         1.9501e-02,  4.4914e-02,  8.4938e-02,  1.3803e-01,  4.0546e-02,
         9.7044e-03, -5.0661e-02,  1.0248e-01, -6.1914e-03, -2.6611e-01,
        -3.7235e-02,  3.1817e-02,  3.7810e-02,  9.4338e-02, -1.2293e-01,
         1.6396e-01,  1.0947e-02,  7.4587e-02,  6.5756e-03,  1.0494e-01,
        -4.8730e-02, -1.0413e-01,  4.3648e-02, -1.5391e-01, -3.3919e-02,
         2.9309e-01,  2.3293e-01,  9.9310e-04,  1.8258e-01, -7.6309e-02,
        -1.8629e-01,  3.0599e-02,  5.5872e-03, -1.9785e-01, -9.2925e-02,
        -6.7694e-02, -2.3459e-01, -2.4240e-01, -2.3626e-02,  3.0388e-01,
         1.2112e-01, -4.5226e-02,  5.5989e-02, -4.7122e-02, -2.1288e-01,
        -6.7990e-03, -7.8901e-02, -3.4509e-02,  1.1970e-01,  3.6406e-02,
         6.8342

In [53]:
X = model.encode(X, convert_to_tensor=True, show_progress_bar=True)
print(X.shape)
X = X.cpu().numpy()

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

torch.Size([1143, 768])


In [55]:
Y = np.array(Y)

In [57]:
print(X.shape)
print(Y.shape)


(1143, 768)
(1143,)


In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [127]:
from sklearn import svm
from sklearn.svm import SVR

regr = svm.SVR(C=10e10)
regr.fit(X_train, Y_train)

score = regr.score(X_test, Y_test)
Y_pred = regr.predict(X_test[:1])

In [128]:
print(score, Y_pred)

0.9454224925010224 [0.56756579]


In [129]:
def predict(ml_model, svr_model, sentences):
    results = model.encode(sentences, convert_to_tensor=True, show_progress_bar=False)
    results = svr_model.predict(np.array(results.cpu()))
    print(results)

In [130]:
predict(model, regr, ["Mięso wołowe", "Cebula", "Piwo"])

[17.26580143  1.0389475   3.96117868]
